server:
  port: 8085

spring:
  profiles:
    include: jdbc, swagger
    # disable CONDITIONS EVALUATION REPORT
  devtools:
    restart:
      log-condition-evaluation-delta: false
  application:
    name: auth-service

# actuator settings
management:
  health:
    default:
      enabled: true
    db:
      enabled: true
  endpoint:
    health:
      showDetails: always
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, openapi, swaggerui
  metrics:
    distribution:
      slo:
        http.server.requests: 10ms, 50ms, 100ms, 200ms, 300ms, 400ms, 500ms
      percentiles-histogram:
        "[http.server.requests]": true
    export:
      prometheus:
        enabled: true
