spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOSTNAME:localhost}:${KAFKA_PORT:9093}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
#      auto-offset-reset: latest
      bootstrap-servers: ${KAFKA_HOSTNAME:localhost}:${KAFKA_PORT:9093}
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topics:
    appealRequestTopic: appealRequestTopic
    appealResponseTopic: appealResponseTopic
    examinationRequestTopic: examinationRequestTopic
    appealCommandTopic: appealCommandTopic
  retry:
    appealRetryTopic: appealRetryTopic
    appealDeadLetterTopic: appealDeadLetterTopic
    doctorRetryTopic: doctorRetryTopic
    doctorDeadLetterTopic: doctorDeadLetterTopic
    count: 3
    retryTopic: retryTopic

outbox:
  fixed-delay-sending-in-milliseconds: 5000
  lock-at-least-for-string-in-milliseconds: 5000ms
  lock-at-most-for-string-in-milliseconds: 30000ms