{
 "title": "Ambulance-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Jpa query count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, service) (spring_data_repository_invocations_seconds_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{pod=~\"appeal-deployment.*|doctor-deployment.*|nurse-deployment.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{pod=~\"appeal-deployment.*|doctor-deployment.*|nurse-deployment.*\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95 quantile by api",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le,uri) (rate(http_server_requests_seconds_bucket{uri!~\"/actuator/prometheus/.*\", uri!~\"UNKNOWN\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway max query duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(routeId) (spring_cloud_gateway_requests_seconds_max)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 count by service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (routeId) (http_server_requests_seconds_count{httpStatusCode=\"500\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request per seconds by api",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{uri!~\"/actuator/prometheus\", uri!~\"UNKNOWN\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway request per second by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (routeId) (rate(spring_cloud_gateway_requests_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}