spring:
  r2dbc:
    url: r2dbc:postgresql://${R2DS_NURSE_DB_HOSTNAME:localhost}:${R2DS_NURSE_DB_PORT:5436}/${R2DS_NURSE_DB_NAME:nurse}
    username: ${R2DS_NURSE_DB_USERNAME:nurse}
    password: ${R2DS_NURSE_DB_PASSWORD:nurse}
    initialization-mode: always
    pool:
      name: NURSE-SERVICE-POOL
      maxSize: 10
      initialSize: 2
      maxIdleTime: 30m
      validationQuery: "SELECT 1"
  liquibase:
    url: jdbc:postgresql://${R2DS_NURSE_DB_HOSTNAME:localhost}:${R2DS_NURSE_DB_PORT:5436}/${R2DS_NURSE_DB_NAME:nurse}
    user: ${R2DS_NURSE_DB_USERNAME:nurse}
    password: ${R2DS_NURSE_DB_PASSWORD:nurse}
    change-log: classpath:/db/db.changelog.yaml