spring:
  r2dbc:
    url: r2dbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5435}/${RDS_DB_NAME:doctor}
    username: ${RDS_USERNAME:doctor}
    password: ${RDS_PASSWORD:doctor}
    initialization-mode: always
    pool:
      name: DOCTOR-SERVICE-POOL
      maxSize: 10
      initialSize: 2
      maxIdleTime: 30m
      validationQuery: "SELECT 1"
  liquibase:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5435}/${RDS_DB_NAME:doctor}
    user: ${RDS_USERNAME:doctor}
    password: ${RDS_PASSWORD:doctor}
    change-log: classpath:/db/db.changelog.yaml