spring:
  r2dbc:
    url: r2dbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5434}/${RDS_DB_NAME:appeal}
    username: ${RDS_USERNAME:appeal}
    password: ${RDS_PASSWORD:appeal}
    initialization-mode: always
    pool:
      name: APPEAL-SERVICE-POOL
      maxSize: 10
      initialSize: 2
      maxIdleTime: 30m
      validationQuery: "SELECT 1"
  liquibase:
    url: jdbc:postgresql://${RDS_HOSTNAME:localhost}:${RDS_PORT:5434}/${RDS_DB_NAME:appeal}
    user: ${RDS_USERNAME:appeal}
    password: ${RDS_PASSWORD:appeal}
    change-log: classpath:/db/db.changelog.yaml