spring:
  r2dbc:
    url: r2dbc:postgresql://${R2DS_APPEAL_DB_HOSTNAME:localhost}:${R2DS_APPEAL_DB_PORT:5434}/${R2DS_APPEAL_DB_NAME:appeal}
    username: ${R2DS_APPEAL_DB_USERNAME:appeal}
    password: ${R2DS_APPEAL_DB_PASSWORD:appeal}
    initialization-mode: always
    pool:
      name: APPEAL-SERVICE-POOL
      maxSize: 10
      initialSize: 2
      maxIdleTime: 30m
      validationQuery: "SELECT 1"
  liquibase:
    url: jdbc:postgresql://${R2DS_APPEAL_DB_HOSTNAME:localhost}:${R2DS_APPEAL_DB_PORT:5434}/${R2DS_APPEAL_DB_NAME:appeal}
    user: ${R2DS_APPEAL_DB_USERNAME:appeal}
    password: ${R2DS_APPEAL_DB_PASSWORD:appeal}
    change-log: classpath:/db/db.changelog.yaml