spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5434/appeal
    username: appeal
    password: appeal
    initialization-mode: always
    pool:
      name: APPEAL-SERVICE-POOL
      maxSize: 10
      initialSize: 2
      maxIdleTime: 30m
      validationQuery: "SELECT 1"