server:
  port: 8081

spring:
  profiles:
    include: jdbc, swagger
    # disable CONDITIONS EVALUATION REPORT
  devtools:
    restart:
      log-condition-evaluation-delta: false

# actuator settings
management:
  health:
    default:
      enabled: true
    db:
      enabled: true
  endpoint:
    health:
      showDetails: always
  endpoints:
    web:
      exposure:
        include: health, prometheus, info, openapi, swaggerui
  metrics:
    export:
      prometheus:
        enabled: true

