apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: gateway
  labels:
    app: gateway
spec:
  type: LoadBalancer
  ports:
    - port: 7084
      name: gateway
      targetPort: 8084
    - port: 6084
      name: gateway-metrics
      protocol: TCP
      targetPort: 8084
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: andrey4281/gateway-service:0.0.2
          name: gateway
          env:
            - name: APPEAL_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: appeal_service_url
            - name: DOCTOR_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: doctor_service_url
            - name: NURSE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: gateway-config
                  key: nurse_service_url
          ports:
            - containerPort: 8084
          imagePullPolicy: IfNotPresent